@echo off
echo  Iniciando entorno Docker...

echo  Limpiando ejecuciones anteriores (contenedores y volumenes)...
docker compose down -v

echo  Reconstruyendo todas las imagenes (esto puede tardar)...
docker compose build

echo  Levantando bases de datos...
rem (Asumo que tus BBDD se llaman 'db_pedidos' y 'db_productos' en el docker-compose.yml)
docker compose up -d db_pedidos db_productos
echo  Esperando 20 segundos a que las bases de datos esten listas...
timeout /t 20 /nobreak

echo  Levantando Config Server y Registry (Eureka)...
docker compose up -d ms-config-server registry-service
echo  Esperando 25 segundos a que esten listos...
timeout /t 25 /nobreak

echo  Levantando Servidor de Autorizacion...
docker compose up -d ms-authorization-server
echo  Esperando 10 segundos...
timeout /t 10 /nobreak

echo  Levantando el resto de microservicios (Gateway y Logica de Negocio)...
docker compose up -d gateway-service ms-pedidos ms-productos

echo  ¡Todo el sistema esta arriba!
docker compose ps
pause