server:
  port: 9000
  forward-headers-strategy: framework

spring:
  application:
    name: ms-authorization-server

  security:
    oauth2:
      authorizationserver:
        issuer: http://gateway-service:8080

# Desactiva completamente Eureka
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health"
