apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: sistema-pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # ¿ CONFIGURACIÓN BÁSICA ¿
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://ms-config-server:8888"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"

            #  PRODUCTOS 
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: "productos-route"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: "http://ms-productos:8081"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: "Path=/api/productos/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0
              value: "PreserveHostHeader"

            # RUTA PEDIDOS 
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: "pedidos-route"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: "http://ms-pedidos:8082"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: "Path=/api/pedidos/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0
              value: "PreserveHostHeader"

            #  RUTA AUTH TOKEN 
            
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: "auth-token-manual"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: "http://ms-authorization-server:9000"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: "Path=/oauth2/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0
              value: "PreserveHostHeader"

            # 
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://ms-authorization-server:9000"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: sistema-pedidos
spec:
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080