apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pedidos
  namespace: sistema-pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pedidos
  template:
    metadata:
      labels:
        app: ms-pedidos
    spec:
      containers:
        - name: ms-pedidos
          image: ms-pedidos:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://ms-config-server:8888"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/sistema_pedidos_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            
            
            
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: ms-pedidos
  namespace: sistema-pedidos
spec:
  selector:
    app: ms-pedidos
  ports:
    - port: 8082
      targetPort: 8082